/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MorphoLiquidatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MORPHO_MANAGEMENT"
      | "eip712Domain"
      | "finalizePosition"
      | "onMorphoLiquidate"
      | "onMorphoRepay"
      | "optimexDomain"
      | "payment"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Credit"
      | "EIP712DomainChanged"
      | "FinalizePosition"
      | "ForceClose"
      | "Liquidate"
      | "OnMorphoLiquidate"
      | "OnMorphoRepay"
      | "Payment"
      | "ProfitTaken"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MORPHO_MANAGEMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizePosition",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onMorphoLiquidate",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onMorphoRepay",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "optimexDomain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "payment",
    values: [
      AddressLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      boolean,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "MORPHO_MANAGEMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onMorphoLiquidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onMorphoRepay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optimexDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payment", data: BytesLike): Result;
}

export namespace CreditEvent {
  export type InputTuple = [
    positionId: BytesLike,
    token: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    token: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    positionId: string;
    token: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FinalizePositionEvent {
  export type InputTuple = [
    positionId: BytesLike,
    apm: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [positionId: string, apm: string, amount: bigint];
  export interface OutputObject {
    positionId: string;
    apm: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ForceCloseEvent {
  export type InputTuple = [
    positionId: BytesLike,
    totalCollateral: BigNumberish,
    totalPayment: BigNumberish,
    repaidDebt: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    totalCollateral: bigint,
    totalPayment: bigint,
    repaidDebt: bigint
  ];
  export interface OutputObject {
    positionId: string;
    totalCollateral: bigint;
    totalPayment: bigint;
    repaidDebt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidateEvent {
  export type InputTuple = [
    positionId: BytesLike,
    totalCollateral: BigNumberish,
    seizedCollateral: BigNumberish,
    totalPayment: BigNumberish,
    repaidDebt: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    totalCollateral: bigint,
    seizedCollateral: bigint,
    totalPayment: bigint,
    repaidDebt: bigint
  ];
  export interface OutputObject {
    positionId: string;
    totalCollateral: bigint;
    seizedCollateral: bigint;
    totalPayment: bigint;
    repaidDebt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OnMorphoLiquidateEvent {
  export type InputTuple = [
    apm: AddressLike,
    repaidAssets: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [apm: string, repaidAssets: bigint, data: string];
  export interface OutputObject {
    apm: string;
    repaidAssets: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OnMorphoRepayEvent {
  export type InputTuple = [
    apm: AddressLike,
    repaidAssets: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [apm: string, repaidAssets: bigint, data: string];
  export interface OutputObject {
    apm: string;
    repaidAssets: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentEvent {
  export type InputTuple = [
    positionId: BytesLike,
    apm: AddressLike,
    tradeId: BytesLike,
    marketId: BytesLike,
    payer: AddressLike,
    isLiquidated: boolean
  ];
  export type OutputTuple = [
    positionId: string,
    apm: string,
    tradeId: string,
    marketId: string,
    payer: string,
    isLiquidated: boolean
  ];
  export interface OutputObject {
    positionId: string;
    apm: string;
    tradeId: string;
    marketId: string;
    payer: string;
    isLiquidated: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfitTakenEvent {
  export type InputTuple = [
    positionId: BytesLike,
    token: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    token: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    positionId: string;
    token: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MorphoLiquidator extends BaseContract {
  connect(runner?: ContractRunner | null): MorphoLiquidator;
  waitForDeployment(): Promise<this>;

  interface: MorphoLiquidatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MORPHO_MANAGEMENT: TypedContractMethod<[], [string], "view">;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  finalizePosition: TypedContractMethod<
    [apm: AddressLike, positionId: BytesLike, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  onMorphoLiquidate: TypedContractMethod<
    [repaidAssets: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  onMorphoRepay: TypedContractMethod<
    [repaidAssets: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  optimexDomain: TypedContractMethod<
    [],
    [[string, string] & { name: string; version: string }],
    "view"
  >;

  payment: TypedContractMethod<
    [
      apm: AddressLike,
      positionId: BytesLike,
      tradeId: BytesLike,
      amount: BigNumberish,
      isLiquidate: boolean,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MORPHO_MANAGEMENT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "finalizePosition"
  ): TypedContractMethod<
    [apm: AddressLike, positionId: BytesLike, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onMorphoLiquidate"
  ): TypedContractMethod<
    [repaidAssets: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onMorphoRepay"
  ): TypedContractMethod<
    [repaidAssets: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "optimexDomain"
  ): TypedContractMethod<
    [],
    [[string, string] & { name: string; version: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "payment"
  ): TypedContractMethod<
    [
      apm: AddressLike,
      positionId: BytesLike,
      tradeId: BytesLike,
      amount: BigNumberish,
      isLiquidate: boolean,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Credit"
  ): TypedContractEvent<
    CreditEvent.InputTuple,
    CreditEvent.OutputTuple,
    CreditEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "FinalizePosition"
  ): TypedContractEvent<
    FinalizePositionEvent.InputTuple,
    FinalizePositionEvent.OutputTuple,
    FinalizePositionEvent.OutputObject
  >;
  getEvent(
    key: "ForceClose"
  ): TypedContractEvent<
    ForceCloseEvent.InputTuple,
    ForceCloseEvent.OutputTuple,
    ForceCloseEvent.OutputObject
  >;
  getEvent(
    key: "Liquidate"
  ): TypedContractEvent<
    LiquidateEvent.InputTuple,
    LiquidateEvent.OutputTuple,
    LiquidateEvent.OutputObject
  >;
  getEvent(
    key: "OnMorphoLiquidate"
  ): TypedContractEvent<
    OnMorphoLiquidateEvent.InputTuple,
    OnMorphoLiquidateEvent.OutputTuple,
    OnMorphoLiquidateEvent.OutputObject
  >;
  getEvent(
    key: "OnMorphoRepay"
  ): TypedContractEvent<
    OnMorphoRepayEvent.InputTuple,
    OnMorphoRepayEvent.OutputTuple,
    OnMorphoRepayEvent.OutputObject
  >;
  getEvent(
    key: "Payment"
  ): TypedContractEvent<
    PaymentEvent.InputTuple,
    PaymentEvent.OutputTuple,
    PaymentEvent.OutputObject
  >;
  getEvent(
    key: "ProfitTaken"
  ): TypedContractEvent<
    ProfitTakenEvent.InputTuple,
    ProfitTakenEvent.OutputTuple,
    ProfitTakenEvent.OutputObject
  >;

  filters: {
    "Credit(bytes32,address,address,uint256)": TypedContractEvent<
      CreditEvent.InputTuple,
      CreditEvent.OutputTuple,
      CreditEvent.OutputObject
    >;
    Credit: TypedContractEvent<
      CreditEvent.InputTuple,
      CreditEvent.OutputTuple,
      CreditEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "FinalizePosition(bytes32,address,uint256)": TypedContractEvent<
      FinalizePositionEvent.InputTuple,
      FinalizePositionEvent.OutputTuple,
      FinalizePositionEvent.OutputObject
    >;
    FinalizePosition: TypedContractEvent<
      FinalizePositionEvent.InputTuple,
      FinalizePositionEvent.OutputTuple,
      FinalizePositionEvent.OutputObject
    >;

    "ForceClose(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      ForceCloseEvent.InputTuple,
      ForceCloseEvent.OutputTuple,
      ForceCloseEvent.OutputObject
    >;
    ForceClose: TypedContractEvent<
      ForceCloseEvent.InputTuple,
      ForceCloseEvent.OutputTuple,
      ForceCloseEvent.OutputObject
    >;

    "Liquidate(bytes32,uint256,uint256,uint256,uint256)": TypedContractEvent<
      LiquidateEvent.InputTuple,
      LiquidateEvent.OutputTuple,
      LiquidateEvent.OutputObject
    >;
    Liquidate: TypedContractEvent<
      LiquidateEvent.InputTuple,
      LiquidateEvent.OutputTuple,
      LiquidateEvent.OutputObject
    >;

    "OnMorphoLiquidate(address,uint256,bytes)": TypedContractEvent<
      OnMorphoLiquidateEvent.InputTuple,
      OnMorphoLiquidateEvent.OutputTuple,
      OnMorphoLiquidateEvent.OutputObject
    >;
    OnMorphoLiquidate: TypedContractEvent<
      OnMorphoLiquidateEvent.InputTuple,
      OnMorphoLiquidateEvent.OutputTuple,
      OnMorphoLiquidateEvent.OutputObject
    >;

    "OnMorphoRepay(address,uint256,bytes)": TypedContractEvent<
      OnMorphoRepayEvent.InputTuple,
      OnMorphoRepayEvent.OutputTuple,
      OnMorphoRepayEvent.OutputObject
    >;
    OnMorphoRepay: TypedContractEvent<
      OnMorphoRepayEvent.InputTuple,
      OnMorphoRepayEvent.OutputTuple,
      OnMorphoRepayEvent.OutputObject
    >;

    "Payment(bytes32,address,bytes32,bytes32,address,bool)": TypedContractEvent<
      PaymentEvent.InputTuple,
      PaymentEvent.OutputTuple,
      PaymentEvent.OutputObject
    >;
    Payment: TypedContractEvent<
      PaymentEvent.InputTuple,
      PaymentEvent.OutputTuple,
      PaymentEvent.OutputObject
    >;

    "ProfitTaken(bytes32,address,address,uint256)": TypedContractEvent<
      ProfitTakenEvent.InputTuple,
      ProfitTakenEvent.OutputTuple,
      ProfitTakenEvent.OutputObject
    >;
    ProfitTaken: TypedContractEvent<
      ProfitTakenEvent.InputTuple,
      ProfitTakenEvent.OutputTuple,
      ProfitTakenEvent.OutputObject
    >;
  };
}
