/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ITypes {
  export type MPCInfoStruct = {
    mpcL2Address: AddressLike;
    expireTime: BigNumberish;
    mpcL2Pubkey: BytesLike;
    mpcAssetPubkey: BytesLike;
  };

  export type MPCInfoStructOutput = [
    mpcL2Address: string,
    expireTime: bigint,
    mpcL2Pubkey: string,
    mpcAssetPubkey: string
  ] & {
    mpcL2Address: string;
    expireTime: bigint;
    mpcL2Pubkey: string;
    mpcAssetPubkey: string;
  };

  export type TokenInfoStruct = {
    info: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike];
    decimals: BigNumberish;
  };

  export type TokenInfoStructOutput = [
    info: [string, string, string, string, string],
    decimals: bigint
  ] & { info: [string, string, string, string, string]; decimals: bigint };
}

export interface ProtocolFetcherProxyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "getLatestMPCInfo"
      | "getMPCInfo"
      | "getManagementOwner"
      | "getPFeeRate"
      | "getPMMAccounts"
      | "getProtocolState"
      | "getRoleAdmin"
      | "getRoleMember"
      | "getRoleMemberCount"
      | "getRoleMembers"
      | "getTokens"
      | "getVault"
      | "grantRole"
      | "hasRole"
      | "isMPCNode"
      | "isSolver"
      | "isValidNetwork"
      | "isValidPMM"
      | "isValidPMMAccount"
      | "isValidPubkey"
      | "isValidToken"
      | "numOfPMMAccounts"
      | "numOfSupportedTokens"
      | "pManagement"
      | "registry"
      | "renounceRole"
      | "revokeRole"
      | "router"
      | "setProtocolManagement"
      | "setRouter"
      | "setSignerExtension"
      | "setVaultRegistry"
      | "signerExtension"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestMPCInfo",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMPCInfo",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getManagementOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPFeeRate",
    values: [[BytesLike, BytesLike, BytesLike, BytesLike]]
  ): string;
  encodeFunctionData(
    functionFragment: "getPMMAccounts",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProtocolState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMember",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMemberCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMembers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokens",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVault",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMPCNode",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSolver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidNetwork",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidPMM",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidPMMAccount",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidPubkey",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidToken",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "numOfPMMAccounts",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "numOfSupportedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pManagement",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setProtocolManagement",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRouter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSignerExtension",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVaultRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signerExtension",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestMPCInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMPCInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getManagementOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPMMAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProtocolState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMPCNode", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isSolver", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidNetwork",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isValidPMM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidPMMAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidPubkey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numOfPMMAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numOfSupportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pManagement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolManagement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSignerExtension",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVaultRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerExtension",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProtocolFetcherProxy extends BaseContract {
  connect(runner?: ContractRunner | null): ProtocolFetcherProxy;
  waitForDeployment(): Promise<this>;

  interface: ProtocolFetcherProxyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  getLatestMPCInfo: TypedContractMethod<
    [networkId: BytesLike],
    [ITypes.MPCInfoStructOutput],
    "view"
  >;

  getMPCInfo: TypedContractMethod<
    [networkId: BytesLike, pubkey: BytesLike],
    [ITypes.MPCInfoStructOutput],
    "view"
  >;

  getManagementOwner: TypedContractMethod<[], [string], "view">;

  getPFeeRate: TypedContractMethod<
    [pairInfo: [BytesLike, BytesLike, BytesLike, BytesLike]],
    [bigint],
    "view"
  >;

  getPMMAccounts: TypedContractMethod<
    [pmmId: BytesLike, fromIdx: BigNumberish, toIdx: BigNumberish],
    [string[]],
    "view"
  >;

  getProtocolState: TypedContractMethod<[], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getRoleMember: TypedContractMethod<
    [role: BytesLike, index: BigNumberish],
    [string],
    "view"
  >;

  getRoleMemberCount: TypedContractMethod<[role: BytesLike], [bigint], "view">;

  getRoleMembers: TypedContractMethod<[role: BytesLike], [string[]], "view">;

  getTokens: TypedContractMethod<
    [fromIdx: BigNumberish, toIdx: BigNumberish],
    [ITypes.TokenInfoStructOutput[]],
    "view"
  >;

  getVault: TypedContractMethod<
    [networkId: BytesLike, tokenId: BytesLike],
    [string],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isMPCNode: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isSolver: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isValidNetwork: TypedContractMethod<
    [networkId: BytesLike],
    [boolean],
    "view"
  >;

  isValidPMM: TypedContractMethod<[pmmId: BytesLike], [boolean], "view">;

  isValidPMMAccount: TypedContractMethod<
    [pmmId: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isValidPubkey: TypedContractMethod<
    [networkId: BytesLike, pubkey: BytesLike],
    [boolean],
    "view"
  >;

  isValidToken: TypedContractMethod<
    [networkId: BytesLike, tokenId: BytesLike],
    [boolean],
    "view"
  >;

  numOfPMMAccounts: TypedContractMethod<[pmmId: BytesLike], [bigint], "view">;

  numOfSupportedTokens: TypedContractMethod<[], [bigint], "view">;

  pManagement: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  router: TypedContractMethod<[], [string], "view">;

  setProtocolManagement: TypedContractMethod<
    [newManagement: AddressLike],
    [void],
    "nonpayable"
  >;

  setRouter: TypedContractMethod<
    [newRouter: AddressLike],
    [void],
    "nonpayable"
  >;

  setSignerExtension: TypedContractMethod<
    [newSignerExtension: AddressLike],
    [void],
    "nonpayable"
  >;

  setVaultRegistry: TypedContractMethod<
    [newRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  signerExtension: TypedContractMethod<[], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLatestMPCInfo"
  ): TypedContractMethod<
    [networkId: BytesLike],
    [ITypes.MPCInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMPCInfo"
  ): TypedContractMethod<
    [networkId: BytesLike, pubkey: BytesLike],
    [ITypes.MPCInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getManagementOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPFeeRate"
  ): TypedContractMethod<
    [pairInfo: [BytesLike, BytesLike, BytesLike, BytesLike]],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPMMAccounts"
  ): TypedContractMethod<
    [pmmId: BytesLike, fromIdx: BigNumberish, toIdx: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProtocolState"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleMember"
  ): TypedContractMethod<
    [role: BytesLike, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleMemberCount"
  ): TypedContractMethod<[role: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleMembers"
  ): TypedContractMethod<[role: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTokens"
  ): TypedContractMethod<
    [fromIdx: BigNumberish, toIdx: BigNumberish],
    [ITypes.TokenInfoStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVault"
  ): TypedContractMethod<
    [networkId: BytesLike, tokenId: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isMPCNode"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSolver"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidNetwork"
  ): TypedContractMethod<[networkId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidPMM"
  ): TypedContractMethod<[pmmId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidPMMAccount"
  ): TypedContractMethod<
    [pmmId: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isValidPubkey"
  ): TypedContractMethod<
    [networkId: BytesLike, pubkey: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isValidToken"
  ): TypedContractMethod<
    [networkId: BytesLike, tokenId: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "numOfPMMAccounts"
  ): TypedContractMethod<[pmmId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "numOfSupportedTokens"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pManagement"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "router"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setProtocolManagement"
  ): TypedContractMethod<[newManagement: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRouter"
  ): TypedContractMethod<[newRouter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSignerExtension"
  ): TypedContractMethod<
    [newSignerExtension: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVaultRegistry"
  ): TypedContractMethod<[newRegistry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signerExtension"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
